# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_post_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
